[Desktop Entry]
Name=parrot
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=ARK-Dark
MetacityTheme=ARK-Dark
IconTheme=ara
GtkColorScheme=fg_color:#EEEEEE,bg_color:#2d2d2d,text_color:#BBBBBB,base_color:#292929,selected_fg_color:#f9f9f9,selected_bg_color:#5179a6,tooltip_fg_color:#dedede,tooltip_bg_color:#2d2d2d
CursorTheme=default
CursorSize=24
NotificationTheme=slider
BackgroundImage=/usr/share/backgrounds/parrot-fly-grey.jpg
